# File: .github/workflows/VIP.yml
name: zero-GithubSync
on: 
  schedule: 
  - cron: '22 2 */3 * *' #此处为同步运行时间
  workflow_dispatch: 
  watch: 
   types: started 
  repository_dispatch:
    types: sync-zero-GithubSync
jobs: 
 repo-sync: 
     env: 
       PAT: ${{ secrets.PAT }}
     runs-on: ubuntu-latest 
     if: github.event.repository.owner.id == github.event.sender.id 
     steps: 
      - uses: actions/checkout@v2 
        with: 
          persist-credentials: false 
           
      - name: sync xxx-GithubSync
        uses: repo-sync/github-sync@v2 
        if: env.PAT 
        with: 
          source_repo: "https://github.com/bullfly666/percollect.git" # 猫一键
          source_branch: "main" 
          destination_branch: "zero205" # 按照自己仓库分支名称修改
          github_token: ${{ secrets.PAT }}
